//
//  CategoriesWireframe.swift
//  GameOfThrones
//
//  Created by Emin on 10.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CategoriesWireframe: BaseWireframe<CategoriesViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Categories", bundle: nil)

    // MARK: - Module setup -

    init(categories:[CategoryItem]) {
        let moduleViewController = storyboard.instantiateViewController(ofType: CategoriesViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = CategoriesInteractor()
        let presenter = CategoriesPresenter(view: moduleViewController,
                                            interactor: interactor,
                                            wireframe: self,
                                            categories: categories)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CategoriesWireframe: CategoriesWireframeInterface {
    func navigateToItemsScene(items: [ItemsModelProtocol]) {
        // TODO: Will be implement
    }
    
}
