//
//  DetailsInteractor.swift
//  GameOfThrones
//
//  Created by Emin on 12.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailsInteractor {
}

// MARK: - Extensions -

extension DetailsInteractor: DetailsInteractorInterface {
}
