//
//  DetailsPresenter.swift
//  GameOfThrones
//
//  Created by Emin on 12.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailsPresenter {

    // MARK: - Private properties -

    private unowned let view: DetailsViewInterface
    private let interactor: DetailsInteractorInterface
    private let wireframe: DetailsWireframeInterface

    private let item: ItemsModelProtocol
    // MARK: - Lifecycle -

    init(
        view: DetailsViewInterface,
        interactor: DetailsInteractorInterface,
        wireframe: DetailsWireframeInterface,
        item:ItemsModelProtocol
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.item = item 
    }
}

// MARK: - Extensions -

extension DetailsPresenter: DetailsPresenterInterface {
    func viewDidLoad() {
        
        var image: UIImage?
        if let imageName: String = (item as? HousesResponseElement)?.region{
           image = UIImage(named: imageName)
        }
        
        let jsonText = item.toJSONString()
        
        view.updateUI(text: jsonText, image: image)
    }
    
    

    
}

