//
//  DetailsWireframe.swift
//  GameOfThrones
//
//  Created by Emin on 12.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailsWireframe: BaseWireframe<DetailsViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Details", bundle: nil)

    // MARK: - Module setup -

    init(item:ItemsModelProtocol) {
        let moduleViewController = storyboard.instantiateViewController(ofType: DetailsViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = DetailsInteractor()
        let presenter = DetailsPresenter(view: moduleViewController, interactor: interactor, wireframe: self, item: item)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailsWireframe: DetailsWireframeInterface {
}
