//
//  ItemsWireframe.swift
//  GameOfThrones
//
//  Created by Emin on 12.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ItemsWireframe: BaseWireframe<ItemsViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Items", bundle: nil)

    // MARK: - Module setup -

    init(items:[ItemsModelProtocol]) {
        let moduleViewController = storyboard.instantiateViewController(ofType: ItemsViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = ItemsInteractor()
        let presenter = ItemsPresenter(view: moduleViewController, interactor: interactor, wireframe: self, items: items)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ItemsWireframe: ItemsWireframeInterface {
    
    func navigateToDetailScene(item: ItemsModelProtocol) {
        navigationController?.pushWireframe(DetailsWireframe(item: item))
    }
    
}
