//
//  SplashPresenter.swift
//  GameOfThrones
//
//  Created by Emin on 10.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SplashPresenter {

    // MARK: - Private properties -

    private unowned let view: SplashViewInterface
    private let interactor: SplashInteractorInterface
    private let wireframe: SplashWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: SplashViewInterface,
        interactor: SplashInteractorInterface,
        wireframe: SplashWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension SplashPresenter: SplashPresenterInterface {
    func viewDidLoad() {
        interactor.loadCategories { [weak self] result in
            guard let self = self else { return }
            switch result {
                
            case .success(let categories):
                self.wireframe.navigateToategories(categories: categories)
            case .failure(_):
                self.wireframe.showAlert(with: "Error", message: "Failed to fetch categories")
            }
        }
    }
    
}
