//
//  SplashWireframe.swift
//  GameOfThrones
//
//  Created by Emin on 10.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SplashWireframe: BaseWireframe<SplashViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Splash", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: SplashViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = SplashInteractor()
        let presenter = SplashPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SplashWireframe: SplashWireframeInterface {
    func navigateToategories(categories: [CategoryItem]) {
        navigationController?.setRootWireframe(CategoriesWireframe(categories: categories))
        
    }
    
}
