//
//  SplashViewController.swift
//  GameOfThrones
//
//  Created by Emin on 10.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SplashViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: SplashPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        presenter.viewDidLoad()
    }

}

// MARK: - Extensions -

extension SplashViewController: SplashViewInterface {
}
