//
//  SplashInterfaces.swift
//  GameOfThrones
//
//  Created by Emin on 10.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SplashWireframeInterface: WireframeInterface {
    
    /// Navigates to Categories Scene with fetched Categories
    /// - Parameter categories: CategoryIte Array
    func navigateToategories(categories:[CategoryItem])
}

protocol SplashViewInterface: ViewInterface {
}

protocol SplashPresenterInterface: PresenterInterface {
    /// Inititates viewDidLoad flow
    func viewDidLoad()
}

protocol SplashInteractorInterface: InteractorInterface {
    /// Loads categories from required entities
    /// - Parameter completion: Completion block for retrieving Categories
    func loadCategories(_ completion:@escaping ((Result<[CategoryItem], APIError>) -> Void))
}
