//
//  ItemsInterfaces.swift
//  GameOfThrones
//
//  Created by Emin on 12.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ItemsWireframeInterface: WireframeInterface {
}

protocol ItemsViewInterface: ViewInterface {
}

protocol ItemsPresenterInterface: PresenterInterface {
    var numberOfRows: Int { get }
    func categoryAtIndex(index:Int, tableView:UITableView) -> ItemsTableCellProtool
    func didSelectRow(index:Int)
}

protocol ItemsInteractorInterface: InteractorInterface {
}
